# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
# frozen_string_literal: true

desc 'Description of what the lane does'
lane :unit_tests do
  scan(
    scheme: 'Gitlab-CI-Demo',
    devices: ['iPhone 11 Pro Max'],
    output_types: 'junit',
    output_files: 'Gitlab-CI-Demo.junit'
  )
end

lane :build do
  build_ios_app(
    scheme: 'Gitlab-CI-Demo',
    output_directory: 'build/',
    archive_path: 'build/',
    output_name: 'app',
    configuration: 'Release',
    include_symbols: true,
    export_method: 'development',
    xcargs: '-allowProvisioningUpdates'
  )
end

lane :bump_version_number do
  build_number = increment_build_number
  commit_version_bump(
    message: "[ci-skip] Version Bump to #{build_number}",
    include: 'Podfile.lock,Gemfile.lock'
  )
end
